# Numpy 배열 출력
- 1D와 2D 배열은 설명하지 않아도 어떻게 출력되는지 확인할수있으나,
- 3D 배열은 2차원이  N개 출력되는 형식으로 나타남



| 3차원 배열 출력하는 코드| (3,4)크기의 2차원 배열이 2개 출력되는 형식
| -- | -- |
| ```c = np.arage(24).reshape(2,3,4) print(c)``` | ```[[[0 1 2 3][4 5 6 7] 8 9 10 11]] [[12 13 14 15][16 17 18 19][20 21 22 23]]]``` |


In [6]:
import numpy as np
# 1차원 배열 출력 
a = np.arange(6)
print(f"1차원 배열 출력:\n{a}\n")

# 2차원 배열 출력
b = np.arange(12).reshape(4,3)
print(f"2차원 배열 출력:\n{b}\n")

# 3차원 배열 출력
# (3,4)크기의 2차원 배열이 2개 출력되는 형식
c = np.arange(24).reshape(2,3,4)
print(f"3차원 배열 출력:\n{c}")

1차원 배열 출력:
[0 1 2 3 4 5]

2차원 배열 출력:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

3차원 배열 출력:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
