# NumPy 배열 대표 속성값
- ndarray.shape : 배열의 각 축(axis)의 크기
- ndarray.ndim : 축의 개수(Dimension)
- ndarray.dtype : 각 요소(Element)의 데이터 타입
- ndarray.size : 각 요소(Element)의 타입의 bytes 크기
- ndarray.itemsize : 각 요소(Element)의 타입의 bytes 크기
- ndarray.nbytes: 전체 요소(Element)의 개수

In [4]:
# a라는 변수에 (3,4)크기의 2D 배열을 생성
import numpy as np
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
# udarray.shpe : 배열의 각 축(axis)의 크기
print(a.shape)
# udarray.ndim : 축의 개수(Dimension)
print(a.ndim)
# udarray.dtype : 각 요소(Element)의 데이터 타입
print(a.dtype)

# ndarray.itemsize : 각 요소(Element)의 타입의 bytes 크기
print(a.itemsize)

# ndarray.size : 전체 요소(Element)의 개수
print(a.size)

(3, 4)
2
int64
8
12


# Numpy 배열 생성
- `np.array`를 이용하여 `Python`에서 사용하는 `Tuple(튜플)`이나 `List(리스트)`를 입력으로 `numpy.ndarray`를 생성
- np.zeros, np.ones, np.empty를 이용하여 다양한 차원의 데이터를 쉽게 생성 가능
    - np.zeros(shape) : 0으로 구성된 N차원 배열 생성
    - np.ones(shape): 1로 구성된 N차원 배열 생성
    - np.empty(shape): 초기화되지 않은 N차원 배열 생성

In [10]:
import numpy as np

a = np.array([2,3,4])
print(a)
print(a.dtype)

[2 3 4]
int64


In [11]:
b= np.array([1.2,3.5,5.1])
print(b)
print(b.dtype)

[1.2 3.5 5.1]
float64


In [ ]:
# (3,4) 크기의 배열을 생성하여 0으로 채움
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# (2,3,4) 크기의 배열을 생성하여 1로 채움
print(np.ones((2,3,4), dtype=np.int64))


[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [19]:
# 초기화 되지않은 (2,3) 크기의 배열을 생성
print(np.empty((2,3)))


[[ 1.79769313e+308 -1.79769313e+308  2.00000000e+000]
 [ 2.22044605e-016  2.22507386e-308  4.94065646e-324]]
